import react from "@vitejs/plugin-react";
import { configDefaults, defineConfig } from "vitest/config";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    environment: "jsdom",
    exclude: [...configDefaults.exclude, "e2e/**"],
    setupFiles: ["./vitest.setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary"],
      include: [
        "components/brand/aelora-mark.tsx",
        "components/auth/sign-in-form.tsx",
        "components/auth/sign-up-form.tsx",
        "components/dashboard/dashboard-overview.tsx",
        "components/configuration/solar-array-form.tsx",
        "components/analytics/historical-analytics.tsx",
        "components/alerts/alerts-dashboard.tsx",
        "components/admin/admin-console.tsx",
        "components/monitoring/live-monitoring.tsx",
        "components/performance/performance-dashboard.tsx",
        "components/reports/reports-dashboard.tsx",
        "components/settings/settings-dashboard.tsx",
        "components/support/help-support-dashboard.tsx",
        "components/forecast/ai-forecast-dashboard.tsx",
        "components/shell/app-shell.tsx",
        "components/shell/app-sidebar.tsx",
        "components/shell/page-placeholder.tsx",
        "lib/navigation.ts",
        "lib/benchmark/statistics.ts",
        "lib/cache/ttl-promise-cache.ts",
        "lib/operations/backup-policy.ts",
        "lib/alerts/detection.ts",
        "lib/alerts/lifecycle.ts",
        "lib/admin/admin.ts",
        "lib/admin/admin-service.ts",
        "lib/configuration/validation.ts",
        "lib/dashboard/snapshot.ts",
        "lib/telemetry/simulator.ts",
        "lib/telemetry/history.ts",
        "lib/telemetry/persisted-snapshot.ts",
        "lib/gateway/contract.ts",
        "lib/gateway/credentials.ts",
        "lib/gateway/ingestion-mapper.ts",
        "lib/gateway/status.ts",
        "lib/performance/performance.ts",
        "lib/performance/performance-service.ts",
        "lib/reports/report.ts",
        "lib/reports/report-pdf.ts",
        "lib/reports/report-service.ts",
        "lib/settings/settings.ts",
        "lib/settings/settings-service.ts",
        "lib/support/support.ts",
        "lib/support/support-service.ts",
        "lib/forecast/ml-client.ts",
        "lib/forecast/forecast-service.ts",
        "lib/weather/open-meteo.ts",
        "lib/weather/sync-auth.ts",
        "lib/weather/weather-service.ts",
        "lib/auth/authorization.ts",
        "lib/auth/route-access.ts",
        "lib/auth/validation.ts",
      ],
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
  },
});
