import { ArrowDownRight, ArrowUpRight, CalendarDays, Download, Gauge, Sparkles, SunMedium, UtilityPole, Zap } from "lucide-react";
import Link from "next/link";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { historyToCsv, type HistoricalTelemetry } from "@/lib/telemetry/history";

function kwh(value: number) { return `${(value / 1000).toFixed(1)} kWh`; }
function chartPoints(values: number[], max: number) { return values.map((value, index) => `${28 + index / Math.max(1, values.length - 1) * 644},${214 - value / max * 168}`).join(" "); }
function comparison(value: number | null) { return value === null ? "No prior data" : `${value >= 0 ? "+" : ""}${value.toFixed(1)}%`; }

export function HistoricalAnalytics({ history }: { history: HistoricalTelemetry }) {
  const maxEnergy = Math.max(1, ...history.points.flatMap((point) => [point.generationWh, point.consumptionWh]));
  const csvHref = `data:text/csv;charset=utf-8,${encodeURIComponent(historyToCsv(history.points))}`;
  const cards = [
    { label: "Generation", value: kwh(history.summary.generationWh), detail: `${comparison(history.comparison.generationChangePct)} vs prior period`, icon: SunMedium },
    { label: "Consumption", value: kwh(history.summary.consumptionWh), detail: `${comparison(history.comparison.consumptionChangePct)} vs prior period`, icon: Zap },
    { label: "Grid import", value: kwh(history.summary.importWh), detail: `Exported ${kwh(history.summary.exportWh)}`, icon: UtilityPole },
    { label: "Solar self-consumption", value: `${history.summary.selfConsumptionPct.toFixed(1)}%`, detail: "Generation used on site", icon: Gauge },
  ];
  return (
    <main className="mx-auto flex w-full max-w-[100rem] flex-col gap-6 px-4 py-7 sm:px-6 sm:py-9 lg:px-8">
      <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Energy history</p><Badge variant="outline">Simulated history</Badge><Badge className="border-energy/25 bg-energy/10 text-energy-strong" variant="outline">{history.completenessPct}% complete</Badge></div><h1 className="mt-3 font-heading text-3xl font-semibold tracking-tight sm:text-4xl">Historical analytics</h1><p className="mt-3 text-muted-foreground">{history.site.name} · stored hourly telemetry, rendered in {history.site.timezone}</p></div><a className="inline-flex h-9 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground" download={`aelora-${history.range.grain}-history.csv`} href={csvHref}><Download aria-hidden="true" className="size-4" />Export CSV</a></header>
      <nav aria-label="Historical range and granularity" className="flex flex-wrap items-center gap-2 rounded-xl border bg-card p-3"><CalendarDays aria-hidden="true" className="mx-1 size-4 text-muted-foreground" />{[7, 30, 90].map((days) => <Link className="rounded-lg border px-3 py-1.5 text-sm hover:bg-accent" href={`?range=${days}&grain=${history.range.grain}`} key={days}>{days} days</Link>)}<span aria-hidden="true" className="mx-1 h-6 w-px bg-border" />{(["day", "week", "month"] as const).map((grain) => <Link className={`rounded-lg px-3 py-1.5 text-sm capitalize ${history.range.grain === grain ? "bg-primary text-primary-foreground" : "border hover:bg-accent"}`} href={`?range=90&grain=${grain}`} key={grain}>{grain}</Link>)}</nav>
      <section aria-label="Historical summary" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, detail, icon: Icon }) => <Card key={label}><CardHeader><span className="grid size-9 place-items-center rounded-lg bg-primary/10 text-primary"><Icon aria-hidden="true" className="size-4.5" /></span><CardDescription className="mt-2">{label}</CardDescription><CardTitle className="text-2xl">{value}</CardTitle></CardHeader><CardContent className="flex items-center gap-1.5 text-xs text-muted-foreground">{detail.startsWith("+") ? <ArrowUpRight aria-hidden="true" className="size-3.5 text-energy-strong" /> : <ArrowDownRight aria-hidden="true" className="size-3.5" />}{detail}</CardContent></Card>)}</section>
      {history.points.length ? <div className="grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(20rem,.55fr)]"><Card><CardHeader><CardTitle><h2>Generation and consumption</h2></CardTitle><CardDescription>Aggregated energy for the selected {history.range.grain} buckets.</CardDescription></CardHeader><CardContent><svg aria-label="Generation and consumption history" className="h-auto w-full" role="img" viewBox="0 0 700 250"><title>Generation and consumption history</title><desc>Amber represents solar generation and blue represents site consumption.</desc>{[46, 102, 158, 214].map((y) => <line className="stroke-border" key={y} x1="28" x2="672" y1={y} y2={y} />)}<polyline className="fill-none stroke-solar [stroke-width:4]" points={chartPoints(history.points.map((point) => point.generationWh), maxEnergy)} strokeLinecap="round" strokeLinejoin="round" /><polyline className="fill-none stroke-primary [stroke-width:3]" points={chartPoints(history.points.map((point) => point.consumptionWh), maxEnergy)} strokeDasharray="7 6" strokeLinecap="round" strokeLinejoin="round" /></svg><div className="flex gap-5 text-xs text-muted-foreground"><span>● Solar generation</span><span>● Consumption</span></div></CardContent></Card><Card><CardHeader><CardTitle><h2>Weather correlation</h2></CardTitle><CardDescription>Irradiance compared with generated energy.</CardDescription></CardHeader><CardContent><svg aria-label="Irradiance versus solar generation" className="h-auto w-full" role="img" viewBox="0 0 360 250"><title>Irradiance versus solar generation</title><line className="stroke-border" x1="30" x2="330" y1="215" y2="215" /><line className="stroke-border" x1="30" x2="30" y1="25" y2="215" />{history.points.map((point, index) => <circle className="fill-solar stroke-solar-strong" cx={30 + point.averageIrradianceWm2 / Math.max(1, ...history.points.map((entry) => entry.averageIrradianceWm2)) * 290} cy={215 - point.generationWh / maxEnergy * 180} key={point.bucketStart} r={4 + index % 2} />)}</svg><p className="text-xs text-muted-foreground">Higher and farther right indicates stronger irradiance and generation.</p></CardContent></Card></div> : <Card><CardHeader><CardTitle>No telemetry in this range</CardTitle><CardDescription>Generate or ingest readings, then choose a range containing stored samples.</CardDescription></CardHeader></Card>}
      <Card className="border-primary/20 bg-primary/5"><CardHeader><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Sparkles aria-hidden="true" className="size-5" /></span><div><CardTitle><h2>Data interpretation</h2></CardTitle><CardDescription className="mt-1 leading-6">These values come from Aelora&apos;s deterministic simulator, not physical meters. Positive grid values are imports; negative readings are reported separately as exports. Completeness compares stored hourly samples with the selected time window.</CardDescription></div></div></CardHeader></Card>
    </main>
  );
}
